version: '3.8'

services:
  backend:
    build:
      context: ..
      dockerfile: docker/Backend.Dockerfile
    ports:
      - "8000:8000"
    environment:
      - AZURE_STORAGE_CONNECTION_STRING=${AZURE_STORAGE_CONNECTION_STRING}
      - AZURE_COSMOS_CONNECTION_STRING=${AZURE_COSMOS_CONNECTION_STRING}
    volumes:
      - ../src/backend/logs:/app/logs

  frontend:
    build:
      context: ..
      dockerfile: docker/Frontend.Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend

networks:
  default:
    name: codegen-network